---
title: "luciole"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{luciole}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
ragg_png <- function(..., res = 150) {
  ragg::agg_png(..., res = res, units = "in")
}

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/",
  out.width = "100%",
  dev = "ragg_png"
)
```

```{r setup}
library(luciole)
```


## ggplot2

Register Luciole font with:

```{r register_luciole}
luciole::register_luciole()
```


The declare the `"Luciole"` family in your graphics:

```{r ggplot2}
library(ggplot2)
ggplot() +
  aes(0, 0, label = "lisibilité") +
  geom_text(size = 10, family = "Luciole") + 
  theme_grey(base_family = "Luciole")
```


In Rstudio, to use Luciole you have to select the ragg device to render plots, see [this excellent blogpost by June Choe ](https://yjunechoe.github.io/posts/2021-06-24-setting-up-and-debugging-custom-fonts/) for more informations.


## Shiny

For using Luciole with all text rendered in HTML in a shiny application, use in your UI:

```{r luciole_font, eval=FALSE}
luciole_font()
```

Example:

```{r shiny, eval=FALSE}

```
